#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. ../wmake/scripts/AllwmakeParseArguments

# Perform various checks
wmakeCheckPwd "$WM_PROJECT_DIR/src" || {
    echo "Allwmake error: Current directory is not \$WM_PROJECT_DIR/src"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Allwmake error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

##SATTIK IFG
OSspecific/${WM_OSTYPE:-POSIX}/Allwmake $targetType $*
Pstream/Allwmake $targetType $*
wmake $targetType OpenFOAM

# Update OpenFOAM version strings if required
wmakePrintBuild -check || wrmo OpenFOAM/global/global.o 2>/dev/null

wmake $targetType fileFormats
wmake $targetType surfMesh
wmake $targetType triSurface

wmake $targetType meshTools
wmake $targetType finiteVolume
wmake $targetType transportModels

thermophysicalModels/Allwmake $targetType $* 
MomentumTransportModels/Allwmake $targetType $*
ThermophysicalTransportModels/Allwmake $targetType $*

mesh/Allwmake $targetType $*
wmake $targetType dynamicMesh
wmake $targetType dynamicFvMesh

wmake $targetType topoChangerFvMesh

wmake $targetType conversion
lagrangian/Allwmake $targetType $*
wmake $targetType sampling

wmake $targetType fvModels
wmake $targetType fvConstraints

dummyThirdParty/Allwmake $targetType $*
regionModels/Allwmake $targetType $*
parallel/Allwmake $targetType $*
wmake $targetType  genericPatchFields
